# Use root/example as user/password credentials
version: '3.8'

services:
  database:
    image: postgres:15
    ports:
      - 3306:5432
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_DB=db_staycation
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./database:/var/lib/postgresql/data